# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionToken',
            fields=[
                ('token', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
