# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='connectiontoken',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.HotelRoom'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hotelroom',
            unique_together=set([('hotel', 'number')]),
        ),
    ]
